# Foundry Configuration File
# =========================
# This file configures the Foundry toolchain for Solidity development.
# It is structured for clarity, maintainability, and easy extension to new networks.

[profile.default]
solc_version = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]
test = "test/helpers"
optimizer = true
optimizer_runs = 800
via_ir = true
gas_reports = ["*"]
auto_detect_solc = false

# Profile for production contracts only
[profile.production]
solc_version = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]
optimizer = true
optimizer_runs = 20000
via_ir = true
auto_detect_solc = false
# Exclude all tests for production builds
test = "test/helpers"

# Profile for unit tests only 
[profile.test-unit]
solc_version = "0.8.23"
src = "src"
out = "out"
libs = ["lib"]
test = "test/unit"
optimizer = true
optimizer_runs = 200
via_ir = true
auto_detect_solc = false

# Profile for integration tests only
[profile.test-integration]
solc_version = "0.8.23"
src = "src"
out = "out"  
libs = ["lib"]
test = "test/integration"
optimizer = true
optimizer_runs = 200
via_ir = true
auto_detect_solc = false

# --- Network RPC Endpoints ---
# Use clear, robust naming for each network.
[rpc_endpoints]
base_mainnet = "https://base-mainnet.g.alchemy.com/v2/i0MCcYy4Gs4p_LVqLAKr1cwF8dGBiYQi"
base_sepolia = "https://base-sepolia.g.alchemy.com/v2/i0MCcYy4Gs4p_LVqLAKr1cwF8dGBiYQi"
celo_mainnet = "https://forno.celo.org"
celo_alfajores = "https://alfajores-forno.celo-testnet.org"
local = "http://127.0.0.1:8545"

# --- Block Explorer API Keys for Verification ---
# Use environment variables for sensitive data.
[etherscan]
base_mainnet = { key = "${BASESCAN_API_KEY}", chain = 8453, url = "https://api.basescan.org/api" }
base_sepolia = { key = "${BASESCAN_API_KEY}", chain = 84532, url = "https://api-sepolia.basescan.org/api" }
celo_mainnet = { key = "${CELOSCAN_API_KEY}", chain = 42220, url = "https://api.celoscan.io/api" }
celo_alfajores = { key = "${CELOSCAN_API_KEY}", chain = 44787, url = "https://api-alfajores.celoscan.io/api" }

# --- Gas Price and Formatting Configurations ---
[fmt]
line_length = 120
tab_width = 4
bracket_spacing = true
int_types = "long"

# --- Testing Configurations ---
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x3e8'
dictionary_weight = 40
include_storage = true
include_push_bytes = true

[invariant]
runs = 256
depth = 15
fail_on_revert = false
call_override = false
dictionary_weight = 80
include_storage = true
include_push_bytes = true
shrink_run_limit = 5000

# --- Additional Notes ---
# - To add new networks, simply add new entries under [rpc_endpoints] and [etherscan].
# - Use environment variables for all sensitive keys and secrets.
# - Keep this file in sync with your deployment scripts for best results.
